{% set name = "eidl" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/haasad/EcoInventDownLoader/archive/{{ version }}.tar.gz
  sha256: 6d6d5735b96c5e7abea7353faae51cb0d916f5779b79d12ba649f4985fc7d732

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - get_ecoinvent = eidl.core:get_ecoinvent_cli

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - appdirs
    - beautifulsoup4
    - bw2data
    - bw2io
    - py7zr
    - python >=3.6
    - requests

test:
  imports:
    - eidl
  # No test of get_ecoinvent as no --help or --version available

about:
  home: https://github.com/haasad/EcoInventDownLoader
  summary: 'EcoInventDownLoader (eidl)'
  description: |
    Download, unpack and import ecoinvent into your brightway2 project in one simple step.
    More details and installation instructions can be found on [github](https://github.com/haasad/EcoInventDownLoader)
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/haasad/EcoInventDownLoader

extra:
  recipe-maintainers:
    - haasad
    - m-rossi
